#pragma once



typedef enum {
    UNI_HAL_CORE_PERIPH_UNKNOWN,
    UNI_HAL_CORE_PERIPH_EMPTY,

    UNI_HAL_CORE_PERIPH_ADC_1,
    UNI_HAL_CORE_PERIPH_ADC_2,
    UNI_HAL_CORE_PERIPH_ADC_3,

    UNI_HAL_CORE_PERIPH_CAN_1,
    UNI_HAL_CORE_PERIPH_CAN_2,

    UNI_HAL_CORE_PERIPH_CRC_1,

    UNI_HAL_CORE_PERIPH_DAC_1,
    UNI_HAL_CORE_PERIPH_DAC_2,

    UNI_HAL_CORE_PERIPH_DMA_1,
    UNI_HAL_CORE_PERIPH_DMA_2,

    UNI_HAL_CORE_PERIPH_ETH_1,

    UNI_HAL_CORE_PERIPH_GPIO_A,
    UNI_HAL_CORE_PERIPH_GPIO_B,
    UNI_HAL_CORE_PERIPH_GPIO_C,
    UNI_HAL_CORE_PERIPH_GPIO_D,
    UNI_HAL_CORE_PERIPH_GPIO_E,
    UNI_HAL_CORE_PERIPH_GPIO_F,
    UNI_HAL_CORE_PERIPH_GPIO_G,
    UNI_HAL_CORE_PERIPH_GPIO_H,
    UNI_HAL_CORE_PERIPH_GPIO_I,

    UNI_HAL_CORE_PERIPH_I2C_1,
    UNI_HAL_CORE_PERIPH_I2C_2,
    UNI_HAL_CORE_PERIPH_I2C_3,
    UNI_HAL_CORE_PERIPH_I2C_4,

    UNI_HAL_CORE_PERIPH_IWDG_1,
    UNI_HAL_CORE_PERIPH_IWDG_2,

    UNI_HAL_CORE_PERIPH_LPUART_1,

    UNI_HAL_CORE_PERIPH_PWR,
    UNI_HAL_CORE_PERIPH_RNG,
    UNI_HAL_CORE_PERIPH_RTC,

    UNI_HAL_CORE_PERIPH_SPI_1,
    UNI_HAL_CORE_PERIPH_SPI_2,
    UNI_HAL_CORE_PERIPH_SPI_3,
    UNI_HAL_CORE_PERIPH_SPI_4,
    UNI_HAL_CORE_PERIPH_SPI_5,
    UNI_HAL_CORE_PERIPH_SPI_6,

    UNI_HAL_CORE_PERIPH_SYSCFG,
    UNI_HAL_CORE_PERIPH_SYSCLK,

    UNI_HAL_CORE_PERIPH_TIM_1,
    UNI_HAL_CORE_PERIPH_TIM_2,
    UNI_HAL_CORE_PERIPH_TIM_3,
    UNI_HAL_CORE_PERIPH_TIM_4,
    UNI_HAL_CORE_PERIPH_TIM_5,
    UNI_HAL_CORE_PERIPH_TIM_6,
    UNI_HAL_CORE_PERIPH_TIM_7,
    UNI_HAL_CORE_PERIPH_TIM_8,
    UNI_HAL_CORE_PERIPH_TIM_9,
    UNI_HAL_CORE_PERIPH_TIM_10,
    UNI_HAL_CORE_PERIPH_TIM_11,
    UNI_HAL_CORE_PERIPH_TIM_12,
    UNI_HAL_CORE_PERIPH_TIM_13,
    UNI_HAL_CORE_PERIPH_TIM_14,
    UNI_HAL_CORE_PERIPH_TIM_15,
    UNI_HAL_CORE_PERIPH_TIM_16,
    UNI_HAL_CORE_PERIPH_TIM_17,

    UNI_HAL_CORE_PERIPH_UART_1,
    UNI_HAL_CORE_PERIPH_UART_2,
    UNI_HAL_CORE_PERIPH_UART_3,
    UNI_HAL_CORE_PERIPH_UART_4,
    UNI_HAL_CORE_PERIPH_UART_5,
    UNI_HAL_CORE_PERIPH_UART_6,
    UNI_HAL_CORE_PERIPH_UART_7,
    UNI_HAL_CORE_PERIPH_UART_8,

} uni_hal_core_periph_e;

typedef enum {
    UNI_HAL_CORE_IRQ_UNKNOWN,

    UNI_HAL_CORE_IRQ_ETH,

    UNI_HAL_CORE_IRQ_EXTI_0,
    UNI_HAL_CORE_IRQ_EXTI_1,
    UNI_HAL_CORE_IRQ_EXTI_2,
    UNI_HAL_CORE_IRQ_EXTI_3,
    UNI_HAL_CORE_IRQ_EXTI_4,
    UNI_HAL_CORE_IRQ_EXTI_5,
    UNI_HAL_CORE_IRQ_EXTI_10,

    UNI_HAL_CORE_IRQ_I2C_1_IRQ1,
    UNI_HAL_CORE_IRQ_I2C_1_IRQ2,
    UNI_HAL_CORE_IRQ_I2C_2_IRQ1,
    UNI_HAL_CORE_IRQ_I2C_2_IRQ2,
    UNI_HAL_CORE_IRQ_I2C_3_IRQ1,
    UNI_HAL_CORE_IRQ_I2C_3_IRQ2,
    UNI_HAL_CORE_IRQ_I2C_4_IRQ1,
    UNI_HAL_CORE_IRQ_I2C_4_IRQ2,

    UNI_HAL_CORE_IRQ_TIM_1,
    UNI_HAL_CORE_IRQ_TIM_15,

    UNI_HAL_CORE_IRQ_UART_1,
    UNI_HAL_CORE_IRQ_UART_2,
    UNI_HAL_CORE_IRQ_UART_3,
    UNI_HAL_CORE_IRQ_UART_4,
    UNI_HAL_CORE_IRQ_UART_5,
    UNI_HAL_CORE_IRQ_UART_6,
    UNI_HAL_CORE_IRQ_UART_7,
    UNI_HAL_CORE_IRQ_UART_8,
} uni_hal_core_irq_e;
