if(CMAKE_C_COMPILER STREQUAL "cl" OR CMAKE_CXX_COMPILER STREQUAL "cl")
    include("${CMAKE_CURRENT_LIST_DIR}/toolchain_compiler_msvc.cmake")
else()
    include("${CMAKE_CURRENT_LIST_DIR}/toolchain_compiler_gcc.cmake")
endif()
